#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

scripts/install/pip_packages pip
# scripts/install/pip_packages setuptools wheel
# scripts/install/pip_packages \
    # --requirement requirements_lint.txt \
    # --requirement requirements_core_min.txt \
    # --requirement requirements_test.txt
scripts/install/pip_packages homeassistant
# scripts/install/frontend

# pre-commit  install --config .github/pre-commit-config.yaml