#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
mkdir -p config

hass --script ensure_config -c config

cd config
ln -sf ../custom_components custom_components

# if ! grep -R "logger" config/configuration.yaml >> /dev/null;then
# echo "
# logger:
#   default: info
#   logs:
#     homeassistant.components.cloud: debug
# " >> config/configuration.yaml
# fi